# apiVersion: v1
# kind: Namespace
# metadata:
#   name: crossplane-system
# ---
apiVersion: v1
kind: Secret
metadata:
  namespace: crossplane-system
  name: providerssh-secret
type: Opaque
stringData:
  config: |
    {
      "username": "",
      "password": "",
      "privateKey": "",
      "hostIP": "",
      "hostPort": "22",
      "knownHosts": ""
    }
---
apiVersion: ssh.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: providerssh-config
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: providerssh-secret
      key: config
